# Generated by Django 3.1.7 on 2021-04-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ManyToManyField(related_name='product_order', to='webapp.Product', verbose_name='продукт')),
            ],
        ),
    ]
